Host he
    HostName 192.168.196.106
    User ubuntu
    Port 50072

Host adam
    HostName 192.168.196.58
    User ubuntu
    Port 50072

Host hinton
    HostName 192.168.196.78
    User ubuntu
    Port 50072

Host lecun
    HostName 192.168.196.176
    User ubuntu
    Port 50072

Host efros
    HostName 192.168.196.227
    User ubuntu
    Port 50072

Host bengio
    HostName 192.168.196.105
    User ubuntu
    Port 50072

Host ian
    HostName 192.168.196.143
    User ubuntu
    Port 50072

Host andrew
    HostName 192.168.196.190
    User ubuntu
    Port 50072

Host ilya
    HostName 192.168.196.63
    User ubuntu
    Port 50072

Host philip
    HostName 192.168.196.150
    User ubuntu
    Port 50072

Host gallego
    HostName 192.168.196.170
    User ubuntu
    Port 50072

Host angjoo
    HostName 192.168.196.238
    User ubuntu
    Port 50072

Host dao
    HostName 192.168.196.56
    User ubuntu
    Port 50072

Host kanade
    HostName 192.168.196.177
    User ubuntu
    Port 50072

Host dlsta
    HostName 192.168.196.54
    User ubuntu
    Port 50072
