"""完了報告の対（result.yaml）から実装の投影を生成する。

    make taskindex          投影を生成する
    make taskindex-check    投影が最新かを検査する

出力は 2 つ。

    context/auto/tasks_summary.csv   1 契約 1 行
    context/auto/followups.md        未処理の申し送りの集約と、起票者の誤りの型の件数

**散文（RESULT.md）は読まない。** 解析して要約を作ると捏造を生む。
読むのは構造化された対（result.yaml）と契約（spec.yaml）だけである。

**壁時計を使わない。** 生成物に日時が混ざると、`--check` が「手による編集」と
「時刻の経過」を区別できなくなる（`tools/build_inbox.py` と同じ方針）。

各生成器は**自分が作る出力だけ**を検査する。`context/auto/` は
`build_context.py` と共有しており、互いの出力を「未知のファイル」と見なさない。
"""

from __future__ import annotations

import argparse
import csv
import difflib
import io
import sys
from collections import Counter
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TASKS_DIR = REPO_ROOT / "tasks"
AUTO_DIR = REPO_ROOT / "context" / "auto"

SUMMARY_NAME = "tasks_summary.csv"
FOLLOWUPS_NAME = "followups.md"

CSV_DECLARATION = (
    "# AUTO-GENERATED by `make taskindex`. DO NOT EDIT. "
    "生成元=tasks/*/result.yaml と spec.yaml"
)
MD_DECLARATION = "<!-- AUTO-GENERATED by `make taskindex`. DO NOT EDIT. -->"
MD_CHECK_NOTICE = "<!-- 手で編集した場合 `make taskindex-check` が検出して失敗します。 -->"

COLUMNS = [
    "task_id", "kind", "status", "host", "pr", "merged",
    "gates_pass", "gates_ask", "gates_stop",
    "tests_before_failed", "tests_after_failed",
    "deviations", "n_issuer_defects", "n_followups", "n_unknowns",
    "depends_on",
]

# result.schema.json の列挙と同じ 4 種。増やす場合は様式の側を先に直す。
DEFECT_TYPES = [
    "check_does_not_check",
    "asserted_without_measuring",
    "self_contradiction",
    "shell_assumption",
]


def collect(tasks_dir: Path) -> list[dict]:
    """対を持つ契約だけを集める。対が無い契約は行に現れない。

    `kind` と `depends_on` は契約（spec.yaml）の側から取る。
    対と契約の両方を読むのは、実行の記録と依頼の記録が別だからである。
    """
    if not tasks_dir.is_dir():
        return []

    rows: list[dict] = []
    for task_dir in sorted(tasks_dir.iterdir()):
        if not task_dir.is_dir() or task_dir.name.startswith("_"):
            continue
        result_path = task_dir / "result.yaml"
        if not result_path.is_file():
            continue
        result = yaml.safe_load(result_path.read_text(encoding="utf-8")) or {}

        spec_path = task_dir / "spec.yaml"
        spec = {}
        if spec_path.is_file():
            spec = yaml.safe_load(spec_path.read_text(encoding="utf-8")) or {}
        meta = spec.get("meta") or {}

        verdicts = Counter(g.get("verdict") for g in (result.get("gates") or []))
        tests = result.get("tests") or {}
        rows.append({
            "task_id": result.get("task_id", task_dir.name),
            "kind": meta.get("kind", ""),
            "status": result.get("status", ""),
            "host": result.get("host", ""),
            "pr": "" if result.get("pr") is None else result.get("pr"),
            "merged": str(bool(result.get("merged"))).lower(),
            "gates_pass": verdicts.get("pass", 0),
            "gates_ask": verdicts.get("ask", 0),
            "gates_stop": verdicts.get("stop", 0),
            "tests_before_failed": tests.get("before_failed", ""),
            "tests_after_failed": tests.get("after_failed", ""),
            "deviations": result.get("deviations", ""),
            "n_issuer_defects": len(result.get("issuer_defects") or []),
            "n_followups": len(result.get("followups") or []),
            "n_unknowns": len(result.get("unknowns") or []),
            "depends_on": " ".join(meta.get("depends_on") or []),
            # 投影の本文づくりに使う。CSV には出さない。
            "_followups": list(result.get("followups") or []),
            "_unknowns": list(result.get("unknowns") or []),
            "_defects": list(result.get("issuer_defects") or []),
        })
    return rows


def render_summary(rows: list[dict]) -> str:
    """1 契約 1 行の表。並びは task_id 順で決定的。"""
    buf = io.StringIO()
    buf.write(CSV_DECLARATION + "\n")
    writer = csv.DictWriter(buf, fieldnames=COLUMNS, lineterminator="\n")
    writer.writeheader()
    for row in sorted(rows, key=lambda r: r["task_id"]):
        writer.writerow({k: row.get(k, "") for k in COLUMNS})
    return buf.getvalue()


def render_followups(rows: list[dict]) -> str:
    """申し送りを集約し、起票者の誤りの型を数える。

    **申し送りの本文は要約せずに転記する。** 由来する契約の識別子を添える。
    """
    ordered = sorted(rows, key=lambda r: r["task_id"])
    lines: list[str] = [
        MD_DECLARATION,
        MD_CHECK_NOTICE,
        "",
        "# followups — 実装からの申し送り",
        "",
        "**このファイルは `tasks/*/result.yaml` から生成される。手で編集しない。**",
        "本文は要約せずに転記している。編集は各契約の `result.yaml` で行う。",
        "",
    ]

    n_items = sum(len(r["_followups"]) for r in ordered)
    lines += [f"## 申し送り（{n_items} 件）", ""]
    if n_items == 0:
        lines += ["（なし）", ""]
    for row in ordered:
        if not row["_followups"]:
            continue
        lines += [f"### {row['task_id']}", ""]
        lines += [f"- {text}" for text in row["_followups"]]
        lines.append("")

    n_unknown = sum(len(r["_unknowns"]) for r in ordered)
    lines += [f"## 断定できなかった事項（{n_unknown} 件）", ""]
    if n_unknown == 0:
        lines += ["（なし）", ""]
    for row in ordered:
        if not row["_unknowns"]:
            continue
        lines += [f"### {row['task_id']}", ""]
        lines += [f"- {text}" for text in row["_unknowns"]]
        lines.append("")

    counts = Counter(d.get("type") for row in ordered for d in row["_defects"])
    total = sum(counts.values())
    lines += [
        f"## 起票者の誤りの型（{total} 件）",
        "",
        "**これは起票者の改善のための記録である。件数を隠さない。**",
        "",
        "| 型 | 件数 |",
        "|---|---:|",
    ]
    for defect_type in DEFECT_TYPES:
        lines.append(f"| `{defect_type}` | {counts.get(defect_type, 0)} |")
    lines += ["", f"合計 {total} 件（対を持つ契約 {len(ordered)} 件から）", ""]
    return "\n".join(lines) + "\n"


def generate(dest: Path, tasks_dir: Path) -> None:
    rows = collect(tasks_dir)
    dest.mkdir(parents=True, exist_ok=True)
    (dest / SUMMARY_NAME).write_text(render_summary(rows), encoding="utf-8")
    (dest / FOLLOWUPS_NAME).write_text(render_followups(rows), encoding="utf-8")


def check(dest: Path, tasks_dir: Path) -> int:
    """**自分が作る 2 ファイルだけ**を検査する。他の生成器の出力には触れない。"""
    rows = collect(tasks_dir)
    fresh = {SUMMARY_NAME: render_summary(rows), FOLLOWUPS_NAME: render_followups(rows)}

    diffs: list[str] = []
    for name, new in fresh.items():
        path = dest / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == new:
            continue
        diffs.append(name)
        print(f"=== {name} ===")
        if old is None:
            print(f"({dest}/{name} が存在しない)")
            continue
        sys.stdout.writelines(
            line + "\n"
            for line in difflib.unified_diff(
                old.splitlines(), new.splitlines(),
                fromfile=f"{name} (現在)", tofile=f"{name} (再生成)", lineterm="",
            )
        )
    if diffs:
        print(f"差分あり: {', '.join(diffs)}。`make taskindex` で再生成すること。")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="再生成して context/auto/ との差分を検査する"
    )
    args = parser.parse_args()

    if args.check:
        return check(AUTO_DIR, TASKS_DIR)

    generate(AUTO_DIR, TASKS_DIR)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
