"""tasks/inbox.d/*.md を集約して tasks/inbox.md を生成する。

判断の受け皿は契約ごとに独立したファイルへ書く。並行して進む契約が別々の
ファイルへ書くため、併合しても元の記録は衝突しない。集約結果はこの道具が
生成する。衝突した場合は再生成すれば解消する。

    make inbox          集約結果を生成する
    make inbox-check    集約結果が最新かを検査する

生成物に日時を書かない。壁時計を使うと、同じ入力でも実行のたびに出力が
変わり、`--check` が「手による編集」と「時刻の経過」を区別できなくなる。
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parents[1]
INBOX_DIR = REPO_ROOT / "tasks" / "inbox.d"
INBOX_FILE = REPO_ROOT / "tasks" / "inbox.md"

DECLARATION = "<!-- AUTO-GENERATED by `make inbox`. DO NOT EDIT. -->"
CHECK_NOTICE = "<!-- 手で編集した場合 `make inbox-check` が検出して失敗します。 -->"

# 項目行の書式: 「- [ ] 」または「- [x] 」で始まる 1 行。
ENTRY_RE = re.compile(r"^- \[(?P<mark>[ xX])\] ")
# 並び順を決めるための日付。項目行の先頭に置かれる規約。
DATE_RE = re.compile(r"^- \[[ xX]\] (?P<date>\d{4}-\d{2}-\d{2})\b")


class Entry(NamedTuple):
    """受け皿の 1 項目。``text`` は元の 1 行をそのまま保持する。"""

    source: str  # 由来したファイル名（例: T-2026-08-11-....md）
    order: int  # そのファイル内での出現順
    date: str  # 並び順に使う日付。取れなければ空文字
    done: bool  # 処理済みなら True
    text: str  # 元の 1 行（一切加工しない）


def collect(inbox_dir: Path) -> list[Entry]:
    """``inbox_dir`` 配下の ``*.md`` から項目行を集める。

    項目行以外（見出し・空行・表）は読み飛ばす。ディレクトリが無い場合は
    空のリストを返す（落とさない）。
    """
    if not inbox_dir.is_dir():
        return []

    entries: list[Entry] = []
    for path in sorted(inbox_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        for order, line in enumerate(text.splitlines()):
            m = ENTRY_RE.match(line)
            if m is None:
                continue
            d = DATE_RE.match(line)
            entries.append(
                Entry(
                    source=path.name,
                    order=order,
                    date=d.group("date") if d else "",
                    done=m.group("mark").lower() == "x",
                    text=line,
                )
            )
    return entries


def _sort_key(e: Entry) -> tuple[str, str, int]:
    """決定的な並び順。日付 → 由来ファイル名 → ファイル内の出現順。

    日付を先に見るのは、集約結果を時系列で読めるようにするため。
    日付が取れない項目は先頭へ寄せる（空文字が最小のため）。
    """
    return (e.date, e.source, e.order)


def render(entries: list[Entry]) -> str:
    """集約結果の本文を組み立てる。同じ入力からは必ず同じ出力になる。"""
    ordered = sorted(entries, key=_sort_key)
    open_items = [e for e in ordered if not e.done]
    done_items = [e for e in ordered if e.done]

    lines: list[str] = [
        DECLARATION,
        CHECK_NOTICE,
        "",
        "# inbox — 判断の受け皿",
        "",
        "**このファイルは `tasks/inbox.d/` から生成される。手で編集しない。**",
        "",
        "判断は契約ごとの記録へ 1 行で置く。",
        "",
        "    tasks/inbox.d/<task_id>.md",
        "",
        "契約ごとに別のファイルへ書くため、並行して進む作業が衝突しない。",
        "このファイルが併合で衝突した場合は、`make inbox` で再生成すれば解消する。",
        "書式と面の一覧は `tasks/README.md` の「判断の受け皿」を参照。",
        "",
        f"## 未処理（{len(open_items)} 件）",
        "",
    ]
    lines.extend(e.text for e in open_items)
    lines.extend(["", f"## 処理済み（{len(done_items)} 件）", ""])
    lines.extend(e.text for e in done_items)
    lines.append("")
    return "\n".join(lines) + "\n"


def check(dest: Path, inbox_dir: Path) -> int:
    """``dest`` が ``inbox_dir`` から再生成した内容と一致するかを検査する。

    差分があれば unified diff を出して 1 を返す。一致すれば 0 を返す。
    """
    fresh = render(collect(inbox_dir))
    old = dest.read_text(encoding="utf-8") if dest.exists() else None

    if old == fresh:
        return 0

    if old is None:
        print(f"{dest} が存在しない。`make inbox` で生成すること。")
        return 1

    sys.stdout.writelines(
        line + "\n"
        for line in difflib.unified_diff(
            old.splitlines(),
            fresh.splitlines(),
            fromfile=f"{dest.name} (現在)",
            tofile=f"{dest.name} (再生成)",
            lineterm="",
        )
    )
    print(f"差分あり: {dest.name}。`make inbox` で再生成すること。")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="再生成して tasks/inbox.md との差分を検査する"
    )
    args = parser.parse_args()

    if args.check:
        return check(INBOX_FILE, INBOX_DIR)

    INBOX_FILE.write_text(render(collect(INBOX_DIR)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
