#!/usr/bin/env python3
"""runindex から軽量ビュー context/auto/ を冪等に生成する。

判断・解釈・評価は書かない。壁時計は使わず、HEAD のコミット日時と commit を使う。
"""
from __future__ import annotations

import argparse
import ast
import csv
import difflib
import re
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
RUNINDEX_DIR = REPO_ROOT / "runindex"
AUTO_DIR = REPO_ROOT / "context" / "auto"
HARVESTER_PATH = REPO_ROOT / "tools" / "harvest_runindex.py"

DECLARATION = "<!-- AUTO-GENERATED by `make context`. DO NOT EDIT. -->"
CHECK_NOTICE = "<!-- 手で編集した場合 `make context-check` が検出して失敗します。 -->"

EXP_SUMMARY_COLUMNS = [
    "experiment_id", "group", "step", "description",
    "arm", "control_of", "task_ids",
    "n_runs", "n_seeds", "hosts", "split",
    "primary_mean", "primary_pstd", "primary_sstd",
    "delta_primary", "delta_pstd_primary", "abs_delta_over_sigma_primary",
    "verdict_metric", "verdict_10_1", "verdict_10_1_sstd", "verdict_10_1_agree",
    "sigma_source", "delta_sigma_source", "sigma_interpretation",
]

VERDICT_SUMMARY_COLUMNS = [
    "experiment_id", "metric", "sigma_source", "arm", "control_of",
    "delta_method", "delta_dedup_rule", "n_seeds", "delta", "pstd", "sstd",
    "ratio_pstd", "ratio_sstd", "same_sign", "verdict_pstd", "verdict_sstd",
    "agree", "reason",
]

_BACKLOG_ID_RE = re.compile(r"^\|\s*(~~)?(BL-[A-Za-z0-9_-]+)")


def _run_git(args: list[str]) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=False
    ).stdout.strip()


STAMP_PATH = "runindex/"


def resolve_stamp_source() -> dict[str, str]:
    """生成物のスタンプ元を返す。

    context/auto/ は runindex/ の投影であり、HEAD の状態ではない。
    HEAD を使うと context/auto/ 自身の commit で陳腐化するため、
    runindex/ を最後に変更した commit を基準にする。
    """
    out = _run_git(["log", "-1", "--format=%H%x09%cI", "--", STAMP_PATH])
    if not out:
        return {"path": STAMP_PATH, "commit": "UNKNOWN", "date": "UNKNOWN"}
    commit, date = out.split("\t", 1)
    return {"path": STAMP_PATH, "commit": commit, "date": date}


def _commit_info() -> tuple[str, str]:
    source = resolve_stamp_source()
    return source["commit"], source["date"]


def _rows(name: str) -> list[dict[str, str]]:
    path = RUNINDEX_DIR / name
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _load_backlog_text() -> str | None:
    """tools/harvest_runindex.py の BACKLOG を ast.literal_eval で読む。"""
    src = HARVESTER_PATH.read_text(encoding="utf-8")
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "BACKLOG" for t in node.targets
        ):
            try:
                value = ast.literal_eval(node.value)
            except (ValueError, SyntaxError):
                return None
            return value if isinstance(value, str) else None
    return None


_BACKLOG_ROW_CELLS = 5  # id | # | 事項 | 分かっていること | 着手の前提


def _parse_backlog_entries(text: str) -> tuple[list[dict[str, Any]], int]:
    """slug・番号・重大度（🔴 マーカー）・見出しのみを抽出する。本文は載せない。

    列数が想定（5 列）と食い違う行は本文へ含めず、skipped の件数として返す。
    本文中の縦線混入（B-33 と同型）は列数を増やすので、`< 3` ではなく
    **ちょうど 5 列**を要求しないと、見出しが静かに切り詰められて誤ったまま
    通ってしまう。
    """
    entries: list[dict[str, Any]] = []
    skipped = 0
    for line in text.splitlines():
        line = line.strip()
        if not _BACKLOG_ID_RE.match(line):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != _BACKLOG_ROW_CELLS:
            skipped += 1
            continue
        raw_id, raw_num, raw_heading = cells[0], cells[1], cells[2]
        resolved = raw_id.startswith("~~") and raw_id.endswith("~~")
        slug = raw_id.strip("~").strip()
        num = raw_num.strip("~").strip()
        heading_raw = raw_heading.strip("~").strip()
        flagged = "🔴" in heading_raw
        heading = heading_raw.replace("🔴", "").replace("**", "").strip()
        # markdown 表へ出力する前に、本文由来の縦線を必ずエスケープする（B-33 対策）。
        heading = heading.replace("|", "\\|")
        entries.append(
            {"slug": slug, "num": num, "heading": heading, "resolved": resolved, "flagged": flagged}
        )
    return entries, skipped


def build_state() -> str:
    source = resolve_stamp_source()
    commit, date = source["commit"], source["date"]
    index_rows = _rows("index.csv")
    exp_rows = _rows("experiments.csv")
    verdict_rows = _rows("verdicts.csv")
    n_index, n_exp, n_verdict = len(index_rows), len(exp_rows), len(verdict_rows)

    lines: list[str] = [
        DECLARATION,
        CHECK_NOTICE,
        "",
        "# STATE — 数値の現在地",
        "",
        f"    generated_from:        {source['path']}",
        f"    generated_from_commit: {commit}",
        f"    generated_from_date:   {date}",
        f"    runindex_counts:       index={n_index} experiments={n_exp} verdicts={n_verdict}",
        "",
        "このファイルは runindex から機械的に生成されたものです。",
        "判断・解釈・評価は含みません。研究方針は context/plan_mirror.md を参照してください。",
        "",
        "## 母集団",
        "",
    ]

    n_excluded = sum(1 for r in index_rows if r.get("excluded") == "True")
    lines.append(f"- 総 run 数: {n_index}")
    lines.append(f"- 除外: {n_excluded}")
    reason_counts = Counter(
        r.get("exclusion_reason", "") for r in index_rows if r.get("excluded") == "True"
    )
    for reason, count in sorted(reason_counts.items()):
        lines.append(f"  - {reason}: {count}")
    lines.append("")
    lines.append("host 別内訳:")
    host_counts = Counter(r.get("host") or "(null)" for r in index_rows)
    for host, count in sorted(host_counts.items()):
        lines.append(f"  - {host}: {count}")
    lines.append("")

    lines.append("## 実験")
    lines.append("")
    n_control = sum(1 for r in exp_rows if r.get("control_of"))
    lines.append(f"- 総数: {n_exp}")
    lines.append(f"- control_of を持つ数: {n_control}")
    lines.append("group 別内訳:")
    group_counts = Counter(r.get("group") or "(null)" for r in exp_rows)
    for group, count in sorted(group_counts.items()):
        lines.append(f"  - {group}: {count}")
    lines.append("")

    lines.append("## 判定")
    lines.append("")
    verdict_counts = Counter(r.get("verdict_10_1") or "(空)" for r in exp_rows)
    lines.append("verdict_10_1 の値別件数:")
    for v, count in sorted(verdict_counts.items()):
        lines.append(f"  - {v}: {count}")
    n_with_verdict = sum(1 for r in exp_rows if r.get("verdict_10_1"))
    n_agree = sum(1 for r in exp_rows if r.get("verdict_10_1_agree") == "True")
    lines.append(
        f"- 母集団σと標本σの一致率（verdict_10_1_agree=True）: {n_agree}/{n_with_verdict}"
        if n_with_verdict
        else "- 母集団σと標本σの一致率（verdict_10_1_agree=True）: 0/0"
    )
    lines.append("")

    lines.append("## σ の健全性")
    lines.append("")
    interp_counts = Counter(r.get("sigma_interpretation") or "(空)" for r in exp_rows)
    lines.append("sigma_interpretation の値別件数:")
    for v, count in sorted(interp_counts.items()):
        lines.append(f"  - {v}: {count}")
    src_counts = Counter(r.get("sigma_source") or "(空)" for r in exp_rows)
    lines.append("sigma_source の値別件数:")
    for v, count in sorted(src_counts.items()):
        lines.append(f"  - {v}: {count}")
    lines.append("")

    lines.append("## 未解決")
    lines.append("")
    backlog_text = _load_backlog_text()
    if backlog_text is None:
        lines.append("UNKNOWN（BACKLOG を解析できませんでした）")
    else:
        entries, skipped = _parse_backlog_entries(backlog_text)
        open_entries = [e for e in entries if not e["resolved"]]
        resolved_count = len(entries) - len(open_entries)
        flagged_count = sum(1 for e in open_entries if e["flagged"])
        lines.append(f"- backlog 総数: {len(entries)}（未解決 {len(open_entries)} / 解決済み {resolved_count}）")
        lines.append(f"- 未解決のうち 🔴 マーカーあり: {flagged_count}")
        if skipped:
            lines.append(f"- 解析できなかった行: {skipped}（列数が想定と食い違う）")
        lines.append("- slug 一覧: context/auto/open_questions.md を参照")
    lines.append("")

    lines.append("## 契約")
    lines.append("")
    n_with_task = sum(1 for r in index_rows if r.get("task_id"))
    pct = f"{n_with_task / n_index * 100:.1f}%" if n_index else "0.0%"
    lines.append(f"- task_id を持つ run: {n_with_task} / {n_index} ({pct})")
    lines.append("")

    lines.append("## 参照先")
    lines.append("")
    for ref in (
        "runindex/index.csv",
        "runindex/experiments.csv",
        "runindex/verdicts.csv",
        "runindex/anomalies/backlog.md",
        "context/auto/experiments_summary.csv",
        "context/auto/verdicts_summary.csv",
        "context/auto/open_questions.md",
    ):
        lines.append(f"- {ref}")
    lines.append("")

    return "\n".join(lines)


def build_open_questions() -> str:
    source = resolve_stamp_source()
    commit, date = source["commit"], source["date"]
    lines: list[str] = [
        DECLARATION,
        CHECK_NOTICE,
        "",
        "# open_questions — 未解決事項",
        "",
        f"    generated_from:        {source['path']}",
        f"    generated_from_commit: {commit}",
        f"    generated_from_date:   {date}",
        "",
        "backlog（`tools/harvest_runindex.py` の `BACKLOG`）から抽出した未解決事項の一覧。",
        "本文は載せない。詳細は `runindex/anomalies/backlog.md` を参照。",
        "",
    ]

    text = _load_backlog_text()
    if text is None:
        lines.append("UNKNOWN（BACKLOG を解析できませんでした）")
        return "\n".join(lines) + "\n"

    entries, skipped = _parse_backlog_entries(text)
    open_entries = [e for e in entries if not e["resolved"]]
    resolved_count = len(entries) - len(open_entries)

    lines.append("| slug | # | 重大 | 見出し |")
    lines.append("|---|---|---|---|")
    for e in open_entries:
        marker = "🔴" if e["flagged"] else ""
        lines.append(f"| {e['slug']} | {e['num']} | {marker} | {e['heading']} |")
    lines.append("")
    lines.append(f"解決済みとして除外: {resolved_count} 件")
    if skipped:
        lines.append(f"解析できなかった行（列数が想定と食い違う）: {skipped} 件")
    return "\n".join(lines) + "\n"


def build_experiments_summary() -> list[dict[str, str]]:
    rows = _rows("experiments.csv")
    out: list[dict[str, str]] = []
    for r in sorted(rows, key=lambda x: x["experiment_id"]):
        vm = r.get("verdict_metric", "")
        row = {
            c: r.get(c, "")
            for c in (
                "experiment_id", "group", "step", "description",
                "arm", "control_of", "task_ids",
                "n_runs", "n_seeds", "hosts", "split",
                "verdict_metric", "verdict_10_1", "verdict_10_1_sstd", "verdict_10_1_agree",
                "sigma_source", "delta_sigma_source", "sigma_interpretation",
            )
        }
        if vm:
            row["primary_mean"] = r.get(f"{vm}_mean", "")
            row["primary_pstd"] = r.get(f"{vm}_pstd", "")
            row["primary_sstd"] = r.get(f"{vm}_sstd", "")
            row["delta_primary"] = r.get(f"delta_{vm}", "")
            row["delta_pstd_primary"] = r.get(f"delta_pstd_{vm}", "")
            row["abs_delta_over_sigma_primary"] = r.get(f"abs_delta_over_sigma_{vm}", "")
        else:
            # 主指標が判別できない行。未測定ではなく該当なしなので UNKNOWN にはしない。
            for c in (
                "primary_mean", "primary_pstd", "primary_sstd",
                "delta_primary", "delta_pstd_primary", "abs_delta_over_sigma_primary",
            ):
                row[c] = ""
        out.append(row)
    return out


def build_verdicts_summary() -> list[dict[str, str]]:
    """主指標（experiments.csv の verdict_metric）の行だけに絞る。"""
    exp_rows = _rows("experiments.csv")
    primary_by_exp = {r["experiment_id"]: r.get("verdict_metric", "") for r in exp_rows}
    rows = _rows("verdicts.csv")
    out = [
        r
        for r in rows
        if r.get("metric") and primary_by_exp.get(r.get("experiment_id", "")) == r.get("metric")
    ]
    out.sort(key=lambda r: (r["experiment_id"], r["metric"]))
    return out


def _write_csv(
    path: Path, columns: list[str], rows: list[dict[str, str]], commit: str, date: str
) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        fh.write(
            f"# {DECLARATION[5:-4].strip()} generated_from={STAMP_PATH}"
            f" generated_from_commit={commit} generated_from_date={date}\n"
        )
        writer = csv.DictWriter(fh, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            writer.writerow({c: row.get(c, "") for c in columns})


def generate_all(dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    commit, date = _commit_info()
    (dest / "STATE.md").write_text(build_state(), encoding="utf-8")
    (dest / "open_questions.md").write_text(build_open_questions(), encoding="utf-8")
    _write_csv(
        dest / "experiments_summary.csv", EXP_SUMMARY_COLUMNS, build_experiments_summary(), commit, date
    )
    _write_csv(
        dest / "verdicts_summary.csv", VERDICT_SUMMARY_COLUMNS, build_verdicts_summary(), commit, date
    )


def check(dest: Path) -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        generate_all(tmp_path)
        # 🔴 **自分が作る出力だけ**を検査する。context/auto/ は build_taskindex.py と
        #    共有しており、existing を混ぜると相手の出力を「再生成すると存在しなくなる」
        #    として差分に数えてしまう（実測で確認済み）。各生成器が自分の出力を持つ。
        fresh = {p.name for p in tmp_path.iterdir()}
        diffs: list[str] = []
        for name in sorted(fresh):
            old_path, new_path = dest / name, tmp_path / name
            old = old_path.read_text(encoding="utf-8") if old_path.exists() else None
            new = new_path.read_text(encoding="utf-8") if new_path.exists() else None
            if old == new:
                continue
            diffs.append(name)
            print(f"=== {name} ===")
            if old is None:
                print("(context/auto/ に存在しない)")
            elif new is None:
                print("(再生成すると存在しなくなる)")
            else:
                sys.stdout.writelines(
                    line + "\n"
                    for line in difflib.unified_diff(
                        old.splitlines(),
                        new.splitlines(),
                        fromfile=f"{name} (現在)",
                        tofile=f"{name} (再生成)",
                        lineterm="",
                    )
                )
        if diffs:
            print(f"差分あり: {', '.join(diffs)}")
            return 1
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", choices=["state", "questions"], help="単一ファイルのみ生成する")
    parser.add_argument("--check", action="store_true", help="再生成して context/auto/ との差分を検査する")
    args = parser.parse_args()

    if args.check:
        return check(AUTO_DIR)

    if args.only == "state":
        AUTO_DIR.mkdir(parents=True, exist_ok=True)
        (AUTO_DIR / "STATE.md").write_text(build_state(), encoding="utf-8")
        return 0
    if args.only == "questions":
        AUTO_DIR.mkdir(parents=True, exist_ok=True)
        (AUTO_DIR / "open_questions.md").write_text(build_open_questions(), encoding="utf-8")
        return 0

    generate_all(AUTO_DIR)
    return 0


if __name__ == "__main__":
    sys.exit(main())
