"""完了報告の対（result.yaml）から実装の投影を生成する。

    make taskindex          投影を生成する
    make taskindex-check    投影が最新かを検査する

出力は 3 つ。

    context/auto/tasks_summary.csv   1 契約 1 行
    context/auto/followups.md        未処理の申し送りの集約と、起票者の誤りの型の件数
    context/auto/results_recent.md   直近の完了報告の中身を新しい順に転記する

**要約しない。転記する。** 件数だけでは「何が誤っていたか」「指示どおりなら何が
起きたか」が伝わらず、読む側が散文を人手で写すしかなかった。投影は構造化された
記述をそのまま写す。散文の解釈は捏造を生む。

**散文（RESULT.md）は読まない。** 解析して要約を作ると捏造を生む。
読むのは構造化された対（result.yaml）と契約（spec.yaml）だけである。

**壁時計を使わない。** 生成物に日時が混ざると、`--check` が「手による編集」と
「時刻の経過」を区別できなくなる（`tools/build_inbox.py` と同じ方針）。

各生成器は**自分が作る出力だけ**を検査する。`context/auto/` は
`build_context.py` と共有しており、互いの出力を「未知のファイル」と見なさない。
"""

from __future__ import annotations

import argparse
import csv
import difflib
import io
import sys
from collections import Counter
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TASKS_DIR = REPO_ROOT / "tasks"
AUTO_DIR = REPO_ROOT / "context" / "auto"

SUMMARY_NAME = "tasks_summary.csv"
FOLLOWUPS_NAME = "followups.md"
RESULTS_RECENT_NAME = "results_recent.md"

# 直近いくつを載せるか。全件を載せると読めなくなるため上限を置く。
# 5 とした理由: 1 契約の転記が 20〜40 行になるため、5 件で 200 行前後に収まる。
# これは 1 画面では読めないが、探さずに端から読める長さである。
# 超えた分は各契約の result.yaml と tasks_summary.csv にあり、失われない。
RECENT_LIMIT = 5

CSV_DECLARATION = (
    "# AUTO-GENERATED by `make taskindex`. DO NOT EDIT. "
    "生成元=tasks/*/result.yaml と spec.yaml"
)
MD_DECLARATION = "<!-- AUTO-GENERATED by `make taskindex`. DO NOT EDIT. -->"
MD_CHECK_NOTICE = "<!-- 手で編集した場合 `make taskindex-check` が検出して失敗します。 -->"

COLUMNS = [
    "task_id", "kind", "status", "host", "pr", "merged",
    "gates_pass", "gates_ask", "gates_stop",
    "tests_before_failed", "tests_after_failed",
    "deviations", "n_issuer_defects", "n_followups", "n_unknowns",
    "depends_on",
]

# result.schema.json の列挙と同じ 4 種。増やす場合は様式の側を先に直す。
DEFECT_TYPES = [
    "check_does_not_check",
    "asserted_without_measuring",
    "self_contradiction",
    "shell_assumption",
]


def _deviation_count(value: object) -> object:
    """版 1 は件数、版 2 は一覧。要約表には常に件数を出す。"""
    if isinstance(value, list):
        return len(value)
    return "" if value is None else value


def collect(tasks_dir: Path) -> list[dict]:
    """対を持つ契約だけを集める。対が無い契約は行に現れない。

    `kind` と `depends_on` は契約（spec.yaml）の側から取る。
    対と契約の両方を読むのは、実行の記録と依頼の記録が別だからである。
    """
    if not tasks_dir.is_dir():
        return []

    rows: list[dict] = []
    for task_dir in sorted(tasks_dir.iterdir()):
        if not task_dir.is_dir() or task_dir.name.startswith("_"):
            continue
        result_path = task_dir / "result.yaml"
        if not result_path.is_file():
            continue
        result = yaml.safe_load(result_path.read_text(encoding="utf-8")) or {}

        spec_path = task_dir / "spec.yaml"
        spec = {}
        if spec_path.is_file():
            spec = yaml.safe_load(spec_path.read_text(encoding="utf-8")) or {}
        meta = spec.get("meta") or {}

        verdicts = Counter(g.get("verdict") for g in (result.get("gates") or []))
        tests = result.get("tests") or {}
        rows.append({
            "task_id": result.get("task_id", task_dir.name),
            "kind": meta.get("kind", ""),
            "status": result.get("status", ""),
            "host": result.get("host", ""),
            "pr": "" if result.get("pr") is None else result.get("pr"),
            "merged": str(bool(result.get("merged"))).lower(),
            "gates_pass": verdicts.get("pass", 0),
            "gates_ask": verdicts.get("ask", 0),
            "gates_stop": verdicts.get("stop", 0),
            "tests_before_failed": tests.get("before_failed", ""),
            "tests_after_failed": tests.get("after_failed", ""),
            # 要約表は 1 契約 1 行で走査するためのものなので、**件数だけ**を出す。
            # 版 2 の一覧をそのまま入れると 1 セルに数百字が入り、表として読めなくなる。
            # 中身は results_recent.md が原文のまま転記する。
            "deviations": _deviation_count(result.get("deviations")),
            "n_issuer_defects": len(result.get("issuer_defects") or []),
            "n_followups": len(result.get("followups") or []),
            "n_unknowns": len(result.get("unknowns") or []),
            "depends_on": " ".join(meta.get("depends_on") or []),
            # 投影の本文づくりに使う。CSV には出さない。
            "_followups": list(result.get("followups") or []),
            "_unknowns": list(result.get("unknowns") or []),
            "_defects": list(result.get("issuer_defects") or []),
            "_gates": list(result.get("gates") or []),
            # 版 1 は整数、版 2 は一覧。**型を揃えない。** 揃えると版 1 の
            # 「件数しか無い」という事実が消え、読む側が中身があると誤解する。
            "_deviations": result.get("deviations"),
            "_version": result.get("result_version"),
        })
    return rows


def render_summary(rows: list[dict]) -> str:
    """1 契約 1 行の表。並びは task_id 順で決定的。"""
    buf = io.StringIO()
    buf.write(CSV_DECLARATION + "\n")
    writer = csv.DictWriter(buf, fieldnames=COLUMNS, lineterminator="\n")
    writer.writeheader()
    for row in sorted(rows, key=lambda r: r["task_id"]):
        writer.writerow({k: row.get(k, "") for k in COLUMNS})
    return buf.getvalue()


def render_followups(rows: list[dict]) -> str:
    """申し送りを集約し、起票者の誤りの型を数える。

    **申し送りの本文は要約せずに転記する。** 由来する契約の識別子を添える。
    """
    ordered = sorted(rows, key=lambda r: r["task_id"])
    lines: list[str] = [
        MD_DECLARATION,
        MD_CHECK_NOTICE,
        "",
        "# followups — 実装からの申し送り",
        "",
        "**このファイルは `tasks/*/result.yaml` から生成される。手で編集しない。**",
        "本文は要約せずに転記している。編集は各契約の `result.yaml` で行う。",
        "",
    ]

    n_items = sum(len(r["_followups"]) for r in ordered)
    lines += [f"## 申し送り（{n_items} 件）", ""]
    if n_items == 0:
        lines += ["（なし）", ""]
    for row in ordered:
        if not row["_followups"]:
            continue
        lines += [f"### {row['task_id']}", ""]
        lines += [f"- {text}" for text in row["_followups"]]
        lines.append("")

    n_unknown = sum(len(r["_unknowns"]) for r in ordered)
    lines += [f"## 断定できなかった事項（{n_unknown} 件）", ""]
    if n_unknown == 0:
        lines += ["（なし）", ""]
    for row in ordered:
        if not row["_unknowns"]:
            continue
        lines += [f"### {row['task_id']}", ""]
        lines += [f"- {text}" for text in row["_unknowns"]]
        lines.append("")

    counts = Counter(d.get("type") for row in ordered for d in row["_defects"])
    total = sum(counts.values())
    lines += [
        f"## 起票者の誤りの型（{total} 件）",
        "",
        "**これは起票者の改善のための記録である。件数を隠さない。**",
        "",
        "| 型 | 件数 |",
        "|---|---:|",
    ]
    for defect_type in DEFECT_TYPES:
        lines.append(f"| `{defect_type}` | {counts.get(defect_type, 0)} |")
    lines += ["", f"合計 {total} 件（対を持つ契約 {len(ordered)} 件から）", ""]
    return "\n".join(lines) + "\n"


def _bullets(items: list[str]) -> list[str]:
    """本文をそのまま箇条書きにする。**切り詰めない。**"""
    return [f"- {text}" for text in items] if items else ["（なし）"]


def render_results_recent(rows: list[dict], limit: int = RECENT_LIMIT) -> str:
    """直近の完了報告の中身を新しい順に転記する。

    **要約しない。** 各項目は `result.yaml` の記述をそのまま写す。
    並びは `task_id` の降順。識別子は `T-YYYY-MM-DD-` で始まるため、
    辞書順の降順がそのまま新しい順になり、壁時計を使わずに決定的である。
    """
    ordered = sorted(rows, key=lambda r: r["task_id"], reverse=True)
    shown, rest = ordered[:limit], max(0, len(ordered) - limit)

    lines: list[str] = [
        MD_DECLARATION,
        MD_CHECK_NOTICE,
        "",
        "# results_recent — 直近の完了報告",
        "",
        "**このファイルは `tasks/*/result.yaml` から生成される。手で編集しない。**",
        "記述は要約せずに転記している。直したいときは各契約の `result.yaml` を直す。",
        "",
    ]
    if not ordered:
        lines += ["対を持つ契約がまだ無い。", ""]
        return "\n".join(lines) + "\n"

    lines += [
        f"新しい順に {len(shown)} 件を載せる（対を持つ契約は全 {len(ordered)} 件）。",
        (
            f"ここに出ない {rest} 件は各契約の `tasks/<task_id>/result.yaml` と "
            "`context/auto/tasks_summary.csv` にある。**失われてはいない。**"
            if rest
            else "全件がここに出ている。"
        ),
        "",
    ]

    for row in shown:
        pr = row["pr"] if row["pr"] != "" else "なし"
        lines += [
            f"## {row['task_id']}",
            "",
            f"状態 `{row['status']}` / ホスト `{row['host']}` / 起票 `{pr}` / "
            f"様式 `v{row['_version']}`",
            "",
            "### ゲート",
            "",
        ]
        if row["_gates"]:
            for gate in row["_gates"]:
                note = gate.get("note")
                head = f"- `{gate.get('id')}` {gate.get('verdict')}"
                lines.append(f"{head} — {note}" if note else f"{head}（記述なし。様式 v1）")
        else:
            lines.append("（なし）")

        lines += ["", "### 起票者の誤り", ""]
        if row["_defects"]:
            lines += [f"- `{d.get('type')}` — {d.get('note')}" for d in row["_defects"]]
        else:
            lines.append("（なし）")

        lines += ["", "### 逸脱", ""]
        deviations = row["_deviations"]
        if isinstance(deviations, list):
            lines += [f"- `{d.get('type')}` — {d.get('note')}" for d in deviations] or ["（なし）"]
        elif deviations in (None, ""):
            lines.append("（なし）")
        else:
            lines.append(f"{deviations} 件（様式 v1 のため件数のみ。中身は RESULT.md にある）")

        lines += ["", "### 申し送り", ""] + _bullets(row["_followups"])
        lines += ["", "### 断定できなかったこと", ""] + _bullets(row["_unknowns"])
        lines.append("")

    return "\n".join(lines) + "\n"


def generate(dest: Path, tasks_dir: Path) -> None:
    rows = collect(tasks_dir)
    dest.mkdir(parents=True, exist_ok=True)
    (dest / SUMMARY_NAME).write_text(render_summary(rows), encoding="utf-8")
    (dest / FOLLOWUPS_NAME).write_text(render_followups(rows), encoding="utf-8")
    (dest / RESULTS_RECENT_NAME).write_text(render_results_recent(rows), encoding="utf-8")


def check(dest: Path, tasks_dir: Path) -> int:
    """**自分が作る 3 ファイルだけ**を検査する。他の生成器の出力には触れない。"""
    rows = collect(tasks_dir)
    fresh = {
        SUMMARY_NAME: render_summary(rows),
        FOLLOWUPS_NAME: render_followups(rows),
        RESULTS_RECENT_NAME: render_results_recent(rows),
    }

    diffs: list[str] = []
    for name, new in fresh.items():
        path = dest / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == new:
            continue
        diffs.append(name)
        print(f"=== {name} ===")
        if old is None:
            print(f"({dest}/{name} が存在しない)")
            continue
        sys.stdout.writelines(
            line + "\n"
            for line in difflib.unified_diff(
                old.splitlines(), new.splitlines(),
                fromfile=f"{name} (現在)", tofile=f"{name} (再生成)", lineterm="",
            )
        )
    if diffs:
        print(f"差分あり: {', '.join(diffs)}。`make taskindex` で再生成すること。")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="再生成して context/auto/ との差分を検査する"
    )
    args = parser.parse_args()

    if args.check:
        return check(AUTO_DIR, TASKS_DIR)

    generate(AUTO_DIR, TASKS_DIR)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
